spring:
  application:
    name: rpamis-usage
  datasource:
    url: jdbc:mysql://localhost:3306/db?characterEncoding=utf-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8181
  servlet:
    context-path: /rpamis-usage